name: linux

on:
  push:
  workflow_dispatch:
    inputs:
      codespace:
        description: 'Name of the codespace to connect to'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Debug in Codespace
      uses: dlemstra/github-actions-debugger@main
      with:
        token: ${{ secrets.TOKEN_FOR_CODESPACES }}
        codespace: ${{ inputs.codespace }}
