name: start-runner

on:
  workflow_dispatch:
    inputs:
      runner:
        description: Name of the runner to use
        required: true
      codespace:
        description: Name of the codespace to connect to
        required: true
      container:
        description: Name of the container to use (optional)
        required: false

permissions:
  contents: read

jobs:
  start-runner:
    name: Start runner on ${{ inputs.runner }}
    runs-on: ${{ inputs.runner }}
    container: ${{ inputs.container != '' && inputs.container || null }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Connect runner to codespace
      uses: dlemstra/github-actions-debugger@main
      with:
        token: ${{ secrets.TOKEN_FOR_CODESPACES }}
        codespace: ${{ inputs.codespace }}
